/**
 * Sequence tracker for @playwright-ordertest/core reporters.
 *
 * Tracks which tests belong to which ordered sequence by parsing project names
 * generated by the plugin. Used by reporters to inject sequence metadata into
 * test results and generate timeline summaries.
 */

import type { ExecutionMode, SequenceMetadata } from '../config/types.js';
import { PROJECT_NAME_PREFIX } from '../config/types.js';
import { debugConsole } from '../logger/logger.js';
import type { Logger } from '../logger/logger.js';

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

/**
 * Execution progress for a single ordered sequence.
 * Tracks step completion counts and per-status test tallies.
 */
export interface SequenceProgress {
  /** Name of the sequence being tracked. */
  readonly sequenceName: string;

  /** Total number of steps (projects) in the sequence. */
  readonly totalSteps: number;

  /** Number of steps that have finished executing. */
  completedSteps: number;

  /** Cumulative count of tests that passed. */
  passedTests: number;

  /** Cumulative count of tests that failed. */
  failedTests: number;

  /** Cumulative count of tests that were skipped. */
  skippedTests: number;

  /** Cumulative count of tests that timed out. */
  timedOutTests: number;
}

/** Parsed components of a generated project name. */
interface ParsedProjectName {
  /** The sequence name extracted from the project name. */
  readonly sequenceName: string;

  /** The 0-based step index extracted from the project name. */
  readonly stepIndex: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse a generated project name into its constituent parts.
 *
 * Expected format: `<PROJECT_NAME_PREFIX>:<sequence-name>:<step-index>`
 * Example: `ordertest:checkout-flow:2` → `{ sequenceName: 'checkout-flow', stepIndex: 2 }`
 *
 * The function handles sequence names defensively: if the name contains colons
 * (which validation should prevent), the last colon-separated segment is treated
 * as the step index and everything before it (after the prefix) is the sequence name.
 *
 * @param name - The Playwright project name to parse
 * @returns Parsed components, or `undefined` if the name does not match the pattern
 */
export function parseProjectName(name: string): ParsedProjectName | undefined {
  const prefix = `${PROJECT_NAME_PREFIX}:`;

  if (!name.startsWith(prefix)) {
    return undefined;
  }

  // Strip the leading "ordertest:" prefix
  const remainder = name.slice(prefix.length);

  // There must be at least one more colon separating sequence name from step index
  const lastColonIndex = remainder.lastIndexOf(':');
  if (lastColonIndex === -1) {
    // No step index segment — not a stepped project (could be "ordertest:unordered")
    return undefined;
  }

  const sequenceName = remainder.slice(0, lastColonIndex);
  const stepIndexRaw = remainder.slice(lastColonIndex + 1);

  if (sequenceName.length === 0) {
    return undefined;
  }

  const stepIndex = Number(stepIndexRaw);
  if (!Number.isInteger(stepIndex) || stepIndex < 0 || stepIndexRaw === '') {
    return undefined;
  }

  return { sequenceName, stepIndex };
}

// ---------------------------------------------------------------------------
// SequenceTracker
// ---------------------------------------------------------------------------

/**
 * Tracks which tests belong to which ordered sequence and records execution progress.
 *
 * Usage:
 * 1. Call `buildFromProjectNames()` with all project names found in the test suite.
 * 2. Use `getSequenceMetadata()` in reporter hooks to annotate individual tests.
 * 3. Call `recordTestStart()` / `recordTestEnd()` to accumulate progress counters.
 * 4. Use `getProgress()` / `getAllSequences()` to build summary reports.
 */
export class SequenceTracker {
  /** Maps project name → sequence metadata. Built by `buildFromProjectNames`. */
  private _sequenceMap: Map<string, SequenceMetadata>;

  /** Tracks execution progress per sequence (keyed by sequence name). */
  private _progress: Map<string, SequenceProgress>;

  /** Optional pino logger for structured file logging. */
  private _logger?: Logger;

  /**
   * Create a new SequenceTracker.
   *
   * @param logger - Optional pino logger for structured activity logging
   */
  constructor(logger?: Logger) {
    this._sequenceMap = new Map();
    this._progress = new Map();
    this._logger = logger;
  }

  /**
   * Build the internal sequence map by inspecting the set of project names
   * produced by the plugin during config generation.
   *
   * This method must be called before any `getSequenceMetadata` or progress
   * tracking calls. It is idempotent — calling it multiple times with the same
   * input produces the same result.
   *
   * @param projectNames - All Playwright project names found in the test suite
   */
  buildFromProjectNames(projectNames: readonly string[]): void {
    debugConsole(
      `buildFromProjectNames: received ${projectNames.length} project name(s): [${projectNames.join(', ')}]`,
    );
    this._logger?.debug(
      { projectNames },
      'sequenceTracker: building sequence map from project names',
    );

    // Reset state so this method is safe to call multiple times
    this._sequenceMap = new Map();
    this._progress = new Map();

    // First pass: collect all parsed entries to determine totalSteps per sequence
    const parsedEntries: Array<{ projectName: string; parsed: ParsedProjectName }> = [];
    const stepCountPerSequence = new Map<string, number>();

    for (const projectName of projectNames) {
      const parsed = parseProjectName(projectName);
      if (parsed === undefined) {
        continue;
      }
      parsedEntries.push({ projectName, parsed });

      const existing = stepCountPerSequence.get(parsed.sequenceName) ?? 0;
      if (parsed.stepIndex + 1 > existing) {
        stepCountPerSequence.set(parsed.sequenceName, parsed.stepIndex + 1);
      }
    }

    // Second pass: build metadata entries now that totalSteps is known
    for (const { projectName, parsed } of parsedEntries) {
      const totalSteps = stepCountPerSequence.get(parsed.sequenceName) ?? 1;
      const humanPosition = `Step ${parsed.stepIndex + 1} of ${totalSteps}`;

      // Derive execution mode from project name — the mode is not embedded in the
      // project name, so we use a neutral default here. Reporters that need the
      // precise mode should cross-reference the Playwright config's project metadata.
      const mode: ExecutionMode = 'serial';

      const metadata: SequenceMetadata = {
        sequenceName: parsed.sequenceName,
        position: humanPosition,
        stepIndex: parsed.stepIndex,
        totalSteps,
        mode,
        isCollapsed: false,
      };

      this._sequenceMap.set(projectName, metadata);

      // Initialise progress entry for this sequence if not yet present
      if (!this._progress.has(parsed.sequenceName)) {
        const progress: SequenceProgress = {
          sequenceName: parsed.sequenceName,
          totalSteps,
          completedSteps: 0,
          passedTests: 0,
          failedTests: 0,
          skippedTests: 0,
          timedOutTests: 0,
        };
        this._progress.set(parsed.sequenceName, progress);
      }
    }

    const sequenceNames = [...stepCountPerSequence.keys()];
    debugConsole(
      `buildFromProjectNames: found ${sequenceNames.length} sequence(s): [${sequenceNames.join(', ')}]`,
    );
    this._logger?.debug(
      { sequenceNames, totalProjects: this._sequenceMap.size },
      'sequenceTracker: sequence map built',
    );
  }

  /**
   * Retrieve sequence metadata for a given Playwright project name.
   *
   * @param projectName - The Playwright project name (e.g. `ordertest:checkout-flow:0`)
   * @returns The `SequenceMetadata` for that project, or `undefined` if the project
   *          is not part of an ordered sequence
   */
  getSequenceMetadata(projectName: string): SequenceMetadata | undefined {
    const metadata = this._sequenceMap.get(projectName);

    debugConsole(
      `getSequenceMetadata("${projectName}"): ${metadata ? `found sequence "${metadata.sequenceName}" ${metadata.position}` : 'not an ordered project'}`,
    );
    this._logger?.debug(
      { projectName, found: metadata !== undefined, metadata },
      'sequenceTracker: getSequenceMetadata',
    );

    return metadata;
  }

  /**
   * Check whether a Playwright project name belongs to an ordered sequence.
   *
   * @param projectName - The Playwright project name to test
   * @returns `true` if the project is part of a tracked ordered sequence
   */
  isOrderedProject(projectName: string): boolean {
    return this._sequenceMap.has(projectName);
  }

  /**
   * Record that a test within a given project has started executing.
   *
   * @param projectName - The Playwright project name the test belongs to
   */
  recordTestStart(projectName: string): void {
    const metadata = this._sequenceMap.get(projectName);

    debugConsole(
      `recordTestStart("${projectName}"): ${metadata ? `sequence "${metadata.sequenceName}"` : 'untracked project'}`,
    );
    this._logger?.debug(
      { projectName, sequenceName: metadata?.sequenceName },
      'sequenceTracker: test started',
    );
  }

  /**
   * Record that a test within a given project has finished, updating per-sequence
   * progress counters.
   *
   * @param projectName - The Playwright project name the test belongs to
   * @param status - Final status of the test
   */
  recordTestEnd(
    projectName: string,
    status: 'passed' | 'failed' | 'skipped' | 'timedOut' | 'interrupted',
  ): void {
    const metadata = this._sequenceMap.get(projectName);

    debugConsole(
      `recordTestEnd("${projectName}", status="${status}"): ${metadata ? `sequence "${metadata.sequenceName}"` : 'untracked project'}`,
    );
    this._logger?.debug(
      { projectName, status, sequenceName: metadata?.sequenceName },
      'sequenceTracker: test ended',
    );

    if (metadata === undefined) {
      return;
    }

    const progress = this._progress.get(metadata.sequenceName);
    if (progress === undefined) {
      return;
    }

    switch (status) {
      case 'passed':
        progress.passedTests += 1;
        break;
      case 'failed':
      case 'interrupted':
        progress.failedTests += 1;
        break;
      case 'skipped':
        progress.skippedTests += 1;
        break;
      case 'timedOut':
        progress.timedOutTests += 1;
        break;
    }

    progress.completedSteps += 1;
  }

  /**
   * Get the current progress for a sequence by its name.
   *
   * @param sequenceName - The sequence name (as defined in the user config)
   * @returns The current `SequenceProgress`, or `undefined` if no such sequence is tracked
   */
  getProgress(sequenceName: string): SequenceProgress | undefined {
    return this._progress.get(sequenceName);
  }

  /**
   * Get the names of all sequences currently tracked by this instance.
   *
   * @returns A read-only array of sequence names, in insertion order
   */
  getAllSequences(): readonly string[] {
    return [...this._progress.keys()];
  }
}
